server.port=${SERVER_PORT:8080}
spring.application.name=risk-backend

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.jackson.default-property-inclusion=non_null

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD}

app.callback-url=${CALLBACK_URL:http://localhost:8080}

app.algorithm.registry-url=${ALGORITHM_REGISTRY_URL:http://localhost:5000}
app.algorithm.sync-interval=${ALGORITHM_SYNC_INTERVAL:60000}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}