# 本地 PostgreSQL 数据库配置
spring.datasource.url=jdbc:postgresql://localhost:5432/neondb?characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=P0o9i8u7
spring.datasource.driver-class-name=org.postgresql.Driver

app.callback-url=http://localhost:8080

app.algorithm.registry-url=http://localhost:5000
app.algorithm.sync-interval=60000

springdoc.api-docs.host=localhost:8080
springdoc.swagger-ui.presets.default=presets/requests-api