spring.datasource.url=jdbc:postgresql://ep-cool-night-amag8gwx-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Q6ISApjOe0cy

app.callback-url=http://localhost:8080

app.algorithm.registry-url=http://localhost:5000
app.algorithm.sync-interval=60000

springdoc.api-docs.host=localhost:8080
springdoc.swagger-ui.presets.default=presets/requests-api