spring.datasource.url=jdbc:postgresql://ep-cool-night-amag8gwx-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Q6ISApjOe0cy

app.callback-url=https://weak-zondra-laosha007-8931c4eb.koyeb.app
app.backend.base-url=https://weak-zondra-laosha007-8931c4eb.koyeb.app

app.algorithm.registry-url=https://sci-risk.onrender.com
app.algorithm.sync-interval=60000
app.algorithm.tariff-endpoint=https://sci-risk.onrender.com/tariff/execute
app.algorithm.scenario-endpoint=https://sci-risk.onrender.com/scenario/execute

springdoc.api-docs.host=weak-zondra-laosha007-8931c4eb.koyeb.app
springdoc.swagger-ui.presets.default=presets/requests-api